# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "wkhtmltopdf-binary-11"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fort Hill Company"]
  s.date = "2013-08-19"
  s.email = "dev@forthillcompany.com"
  s.executables = ["wkhtmltopdf"]
  s.extra_rdoc_files = [
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/wkhtmltopdf",
    "lib/wkhtmltopdf-binary.rb",
    "libexec/wkhtmltopdf-darwin-x86",
    "libexec/wkhtmltopdf-linux-amd64",
    "libexec/wkhtmltopdf-linux-x86",
    "wkhtmltopdf-binary-11.gemspec"
  ]
  s.homepage = "http://github.com/dbatshaw/wkhtmltopdf-binary-11"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Provides 0.11rc binaries for WKHTMLTOPDF project in an easily accessible package."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

